stages:
- mavenbuild
- maventest
- autodeploy


maven-build:
    stage: mavenbuild
    tags: 
        - -BACKEND
    script: 
        - cd Backend/Gitlab_Runner_Build/Runner_Build
        - mvn package -B

maven-test:
    stage: maventest
    tags:
        - -BACKEND
    script:
        - cd Backend/Gitlab_Runner_Build/Runner_Build
        - mvn test
        - mvn package -B
    artifacts:
        paths:
        - Backend/sprintboot-first-app vFinal/target/*.jar

autoDeploy:
    stage: autodeploy
    tags:
        - -BACKEND
    script: 
        - cd Backend/Gitlab_Runner_Build/Runner_Build
        - mvn test
        - mvn package -B
        - mv target/*.jar /target/web-demo.jar
        - cd /
        - sudo systemctl stop web-demo
        - sudo systemctl start web-demo
        - sudo systemctl status web-demo



